### PR TITLE
Add webp image support

### PR DESCRIPTION
**Pull request by NicoleGeissinger**
Adds the ability to generate webp images on upload of jpg and png files which are then uploaded to Azure Storage containers. This is code used on other MS sites 10up manages and was recommended by @rickalee this would be a great addition to the plugin. This MR is the first pass at adding this feature.

By default, this code will enable webp support, so I want to add to the azure storage settings a toggle for turning this feature on/off to give users the option to enable it. It will be off by default.

The MR also features some JS loaded on the front-end to ensure that older browsers that don't support webp fallback to the original image mime type. HOWEVER, considering webp has [95% global support](https://caniuse.com/?search=webp), perhaps we can consider foregoing this fallback script?

NOTE: This MR is a work in progress. Currently, one known bug exists where the image src isn't updated to use a webp image, while the srcset URLs are. I am looking into this and have disabled the fallback JS script to ensure that isn't modifying URLs while debugging.

### Alternate Designs

n/a

### Benefits

This further enhances the Azure Storage plugin by providing WordPress users improved speed by loading smaller image sizes without a perceived reduction in quality. Faster page loads can also greatly benefit SEO rankings.

### Possible Drawbacks

This addition will mean that two versions of the same image (and each size generated by WordPress) will be uploaded to Azure Storage. This will double the number of images when uploading a new image which can lead to longer upload times, and storage in the container.

### Checklist:

- [X] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by NicoleGeissinger** [comment]
An update here, I have found that this implementation needs a little tweaking to ensure this works with Gutenberg enabled. This code is primarily running on non-gutenberg installs at the moment and one of the filters used here is no longer called on the front-end with Gutenberg enabled. I will be looking into an updated version of this so both gutenberg and non-gutenberg install work as expected.

**Comment by NicoleGeissinger** [comment]
I have been able to complete this PR. 

It should be noted that this requires the block editor to 100% support. This is primarily because this feature should be non-destructive to images in the database. On Classic Editor, we had to manipulate image URLs on save. Since this is an optional feature for sites to turn on, the block editor gives us the most non-destructive option for manipulating image paths on the fly while preserving the original image path.

Testing:
* By default webp support is disabled and is opt-in only.
* To enable webp support, go to the Azure Storage Settings in the admin area, and at the bottom of the settings is a checkbox to enable web support.
* Any new image uploaded to WordPress will have a webp version created. This accounts for each image size registered and uploaded to Azure Storage.
* Core image blocks (core/image, core/media-text, and core/cover) are supported. Adding an image to any of these blocks will have its image paths updated on the front-end to the webp version if one exists.
* Image src and srcset paths are updated to webp.
* Any existing images uploaded before enabling this feature will not be auto-converted. To do this, utilize the regenerate thumbnails CLI command or plugin.
* If you generate new webp images, and then decide to turn off the feature, all images will load the original image type.
* There are steps put in place to prevent WPSEO plugin from loading webp images into the Open Graph meta tags, which DO NOT support webp (primarily LinkedIn).
* While webp has [94% support globally](https://caniuse.com/webp), we still feature a fallback script that will ensure the original images are served if webp is not supported.

**Comment by NicoleGeissinger** [comment]
I spoke with @rickalee about this ticket and we want to run some further tests with the work that the [WordPress Performance Team](https://make.wordpress.org/core/2022/03/07/the-performance-lab-plugin-has-been-released/) is running around testing/adding a feature project for webp support in WordPress.

There is work currently that allows the creation of webp images on [uploads](https://github.com/WordPress/performance/issues?q=is%3Aissue+label%3A%22%5BModule%5D+WebP+Uploads%22) and [support](https://github.com/WordPress/performance/issues?q=is%3Aissue+label%3A%22%5BModule%5D+WebP+Support%22) via the Site Health status.

The ultimate goal is to ensure we aren't introducing a new feature that will otherwise be deprecated due to it coming to core. Considering this update does write data to post meta, we want to be sure that this is being handled right and with the ability to support a core update for webp support in the future.

For now, this PR needs a little more work and vetting before it is ready for a release version. Ricky Lee and I will be running further testing and assessing any further changes.

**Comment by jeffpaul** [comment]
@colegeissinger given that WP 6.0 will **NOT** be including WebP support, but that it will likely be back for consideration in WP 6.1 later this year... how do you want to handle things in this PR?

**Comment by jeffpaul** [comment]
@colegeissinger given that WebP support will not likely land in core, but rather via a "Canonical Plugin", and that that will rely on the route the WP Core Performance team takes (possibly within the Performance Lab plugin, possibly a separate one) is there an updated approach you'd like to consider here?

**Comment by jeffpaul** [comment]
@colegeissinger note that https://wordpress.org/plugins/webp-uploads/ is now available, so let me know how/if you want to update here accordingly?

**Comment by NicoleGeissinger** [comment]
Thanks @jeffpaul !! Do you know if the plan from the performance team is to keep this as a plugin or is it still planned for core in the future?

**Comment by jeffpaul** [comment]
@colegeissinger as best I can guess, the [WebP plugin from the Performance team](https://wordpress.org/plugins/webp-uploads/) is staying as a plugin for the foreseeable future.

**Comment by jeffpaul** [comment]
@colegeissinger is this something you still want to get into the plugin or should we close this out as no longer actionable/desired?

**Comment by jeffpaul** [comment]
Closing this as not currently actionable, but open to having this re-opened if someone is able to own the completion and review of this.

**Pull request closed without merging**
