### PR TITLE
Fix WP_Filesystem() During Rest API Calls

### LINKED ISSUE #143: Error with WP_Filesystem() in REST API Calls
**Describe the bug**

The plugin fails when trying to "crop" an image within the Block Editor, causing a corrupt image.

This is because the plugin calls `WP_Filesystem()`, which, although is available in `wp-admin`, is not available during REST API calls, which the Block Editor uses for functionality like image cropping.

**Steps to Reproduce**

1. Create a fresh WordPress site
2. Install the plugin and add all details, and ensure that `Use for default upload` is checked
3. Upload an image in Media -> Add New
4. The image successfully uploads to Azure and all thumbnails are successfully created
5. Create a new post
6. Add the image to the post and publish it
7. The post is successfully created and the image shows correctly
8. Now edit the post and and "Crop" the image (screenshot below) - maybe by zooming in - and apply the crop
9. This now fails - but the user is not aware of the failure
10. If you save the post now and look at it on the front-end, you'll see a corrupt image with incorrect SRCSET values, and none of the images were uploaded to Azure

**Expected behavior**

The plugin works well with functionality in the Block Editor like cropping.

**Screenshots**
Crop the image:
Screen Shot 2021-06-11 at 8 44 34 am

**Environment information**
 - Device: MacBook Pro
 - OS: MacOS 11.4
 - Browser and version: Brave (Chromium: 91.0.4472.77)
 - WordPress version: 5.7.2

**Additional context**

### PR DESCRIPTION
**Pull request by junaidbhura**
### Description of the Change

Ensure that the file that contains `WP_Filesystem()` is included before calling it.

### Verification Process

This has been verified on a fresh install of WordPress by following the steps mentioned in #143 

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

Fixes #143

### CODE REVIEW

**Comment by jeffpaul** [comment]
@rickalee checking in again on review, let me know if there's someone else on the team who can help get this through review and merged

**Review by NicoleGeissinger — DISMISSED** [review]

**Comment by jeffpaul** [comment]
@colegeissinger are you able to help update the merge conflict here?

**Comment by NicoleGeissinger** [comment]
@jeffpaul merge conflict is resolved now, although we need another review of this if anyone from your team can help there? Thanks!

**Comment by jeffpaul** [comment]
@10up/open-source-practice could use a quick code review on this for the 4.4.0 release, thanks!

**Comment by faisal-alvi** [comment]
@jeffpaul The requested changes are already merged in the `develop` via #136. See https://github.com/10up/windows-azure-storage/commit/a2aca22287756cf46a7ed8189e72b68185532372

https://github.com/10up/windows-azure-storage/blob/3b7f2fa776cb5a3d2111ce94258245971a4c1517/includes/class-windows-azure-helper.php#L586-L591

Closing.

**Pull request closed without merging**
