### PR TITLE
Azure Upload Progress Hotfix

### PR DESCRIPTION
**Pull request by rickalee**
Add transient for file uploads to track the progress of offloading to Azure when wp_generate_attachment_metadata runs. Ensure PDF generated thumbnails are offloaded with JPEG mime type instead of PDF.

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jeffpaul** [comment]
@moraleida waiting on your confirmation from testing, please keep us posted, thanks!

**Comment by moraleida** [comment]
@jeffpaul @rickalee this was tested on preprod last week. It did indeed reduce the server load when uploading hundreds of images but something doesn't seem correct about the numbers (percentages and totals) reported in the admin. We'll need to test a bit more to make sure we don't break that.

**Comment by rickalee** [comment]
@moraleida I believe you are correct. I will work on fix to add original_image to count if source is larger than 2560.

**Comment by jeffpaul** [comment]
@rickalee we can close this in favor of #110, correct?

**Comment by rickalee** [comment]
@jeffpaul Yes. #110 includes these changes.

**Pull request closed without merging**
