### PR TITLE
Fix uploading issue in the multisite environment

### PR DESCRIPTION
**Pull request by eugene-manuilov**

### CODE REVIEW

**Comment by rickalee** [comment]
Hi Eugene,

I pulled this down to our local test environment. 

Subsites added sites/{ID}
{container}/sites/113/2018/01/omb_bliss_sky.jpg

Primary site at root uploaded to:
{container}/2018/01/landscape-hilly-trees-46009.jpeg

Inserted image into post content and srcset is showing for both primary and subsites and assets are on Azure and no image size is 404ing. 

I think we are set here if you can confirm this is intended behavior with the primary site in Multisite. 

cc @TheLastCicada Primary site path will be relevant to @engrshakirali

**Comment by eugene-manuilov** [comment]
Thanks, @rickalee! Yes, it is intended behavior. Nice to hear it. @tott can you review this pull request?

**Comment by tott** [comment]
@eugene-manuilov this looks good to me in context of a multi-site setup. I'm not 100% convinced that it will work with new or upgrading single site setups. Did you verify this?

**Comment by eugene-manuilov** [comment]
@tott, yes, looks good on single site setup as well. Why aren't you sure about it?

**Comment by rickalee** [comment]
@tott @eugene-manuilov 

We have been using this branch on two large multisite networks for over a month and also tested with single sites.

Can we possibly get multisite fix and url encoding of special characters in a 4.2.0 version? 

I've synced with master, included special characters fix which has been tested across multiple environments, and updated README, CHANGELOG in this branch.

**Comment by JockeTF** [comment]
Any plans for merging this? I'm depending on multisite support.

**Pull request merged**
