### PR TITLE
Update Azure Storage Service API_VERSION

### LINKED ISSUE #121: Update Azure Blob API to Latest - 2020-04-08
To support more advanced features of Azure Blob Storage we should update API to latest version.

Desired Features:
* Soft Delete/Undelete Blob
* Blob Batch (bulk uploading)

https://docs.microsoft.com/en-us/rest/api/storageservices/versioning-for-the-azure-storage-services

### LINKED ISSUE #143: Error with WP_Filesystem() in REST API Calls
**Describe the bug**

The plugin fails when trying to "crop" an image within the Block Editor, causing a corrupt image.

This is because the plugin calls `WP_Filesystem()`, which, although is available in `wp-admin`, is not available during REST API calls, which the Block Editor uses for functionality like image cropping.

**Steps to Reproduce**

1. Create a fresh WordPress site
2. Install the plugin and add all details, and ensure that `Use for default upload` is checked
3. Upload an image in Media -> Add New
4. The image successfully uploads to Azure and all thumbnails are successfully created
5. Create a new post
6. Add the image to the post and publish it
7. The post is successfully created and the image shows correctly
8. Now edit the post and and "Crop" the image (screenshot below) - maybe by zooming in - and apply the crop
9. This now fails - but the user is not aware of the failure
10. If you save the post now and look at it on the front-end, you'll see a corrupt image with incorrect SRCSET values, and none of the images were uploaded to Azure

**Expected behavior**

The plugin works well with functionality in the Block Editor like cropping.

**Screenshots**
Crop the image:
Screen Shot 2021-06-11 at 8 44 34 am

**Environment information**
 - Device: MacBook Pro
 - OS: MacOS 11.4
 - Browser and version: Brave (Chromium: 91.0.4472.77)
 - WordPress version: 5.7.2

**Additional context**

### PR DESCRIPTION
**Pull request by thrijith**
### Description of the Change

- Updates the blob API version to `2020-04-08`

### Verification Process

- Tested current upload features work after updating the version.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Applicable Issues

Fixes https://github.com/10up/windows-azure-storage/issues/121

### CODE REVIEW

**Comment by NicoleGeissinger** [comment]
I ran a little test locally with a MS site that is on Multisite. I pulled down the branch and ran `npm install && composer install` which all went fine and images continue to load in media library and on the front-end.

I am getting a series of errors when interacting with the plugin, however.  I found I could no longer upload images or delete images. When debugging further I found when I saved the Azure settings it halted due to a fatal error. When debugging, I found all three linked back to the same fatal error below:
```
[21-Jul-2021 18:40:23 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\Psr7\build_query() in /var/www/html/wp-content/plugins/windows-azure-storage/vendor/microsoft/azure-storage-common/src/Common/Internal/ServiceRestProxy.php:300
Stack trace:
#0 /var/www/html/wp-content/plugins/windows-azure-storage/vendor/microsoft/azure-storage-common/src/Common/Internal/ServiceRestProxy.php(364): MicrosoftAzure\Storage\Common\Internal\ServiceRestProxy->createRequest('GET', Array, Array, Array, '/{container-name}', 'PrimaryOnly', '')
#1 /var/www/html/wp-content/plugins/windows-azure-storage/vendor/microsoft/azure-storage-blob/src/Blob/BlobRestProxy.php(500): MicrosoftAzure\Storage\Common\Internal\ServiceRestProxy->sendAsync('GET', Array, Array, Array, '{container-name}', 200, '', Object(MicrosoftAzure\Storage\Blob\Models\BlobServiceOptions))
#2 /var/www/html/wp-content/plugins/windows-azure-storage/vendor/microsoft/azure-storage-blob/src/Blob/BlobRestProxy.php(1076): MicrosoftAzure\Storage\Blob\BlobRestProxy->getContainerPropertiesAsyncImpl('{container-name}', Object(MicrosoftAzure\S in /var/www/html/wp-content/plugins/windows-azure-storage/vendor/microsoft/azure-storage-common/src/Common/Internal/ServiceRestProxy.php on line 300
```

NOTE: I stripped the container name that was in the stack trace to keep that private.
Unsure I'm missing something on my end, so please let me know

**Comment by thrijith** [comment]
> I ran a little test locally with a MS site that is on Multisite. I pulled down the branch and ran npm install && composer install which all went fine and images continue to load in media library and on the front-end.

> I am getting a series of errors when interacting with the plugin, however. I found I could no longer upload images or delete images. When debugging further I found when I saved the Azure settings it halted due to a fatal error. When debugging, I found all three linked back to the same fatal error below:


Hi @colegeissinger thanks for checking this is still WIP, as of now I have updated usage for wp-cli commands, I haven't tested the other features yet. The error you are getting is what I got initially but was fixed automatically when I last tried. I'll let you know once it is ready for review.

**Comment by NicoleGeissinger** [comment]
got it! Thanks, @thrijith ! I'll await your update for when this is ready :)

**Comment by thrijith** [comment]
Hi @colegeissinger 

Please check this when you get a chance, I have updated the internal methods to use the libraries available via vendor.

@jeffpaul since this will require vendor directories present, wanted to confirm if adding it in git is ok.

---

@colegeissinger the main difference I am seeing is the access tier for the blob, below you can see that the previously uploaded blobs didn't have any but newer ones do have it. We can have `Hot`, `Cool` and `Archive`, more info on this can be found here https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-storage-tiers, I have defaulted to `Hot` which can be modified via new filter `windows_azure_blob_access_tier` .

azure-before-after-access-tier

**Comment by jeffpaul** [comment]
Deferring to @helen @dkotter @rickalee on the vendor directories question.

**Comment by dkotter** [comment]
We have other plugins that do version control some things in the `vendor/` directory (like [Distributor](https://github.com/10up/distributor/tree/develop/vendor) or [Classifai](https://github.com/10up/classifai/tree/develop/vendor/)) but the one thing they do that I'm not seeing here is they are very explicit on what we add in that directory, instead of just adding the entire directory. I'd prefer if we are going to add these to version control that we are specific on which dependencies we add and not just add the entire directory.

But I also like an approach where these things aren't version controlled at all but are handled during a build step. I don't know enough about GitHub Actions to know if we're doing this already in other places, but I could see an approach where we version control `composer.json` and `composer.lock` but not the `vendor` directory. And then during our build/release step, `composer install` is run and the dependencies we need are then packaged with the release. This very well may be overkill for this though, just my initial thoughts.

**Comment by thrijith** [comment]
Hi @dkotter both options seem ok to me, I can `vendor` directory to only allow the required dependencies.

For second option, I thinks that's what we have here https://github.com/10up/autoshare-for-twitter/blob/develop/.github/workflows/deploy-to-wpdotorg.yml#L17, automated options seems helpful and we don't have to keep that in git, only issue I can think of is some failure in the build process and release being pushed with missing files required to run the plugin.

**Comment by NicoleGeissinger** [comment]
@thrijith @rickalee I have finally come around to running tests of this. Sorry for the large lapse in time on that...

The first thing I notice is that we have a merge conflict on this branch, @thrijith, when you have a moment, can you resolve these conflicts?

Below are my findings of running tests against this branch. I feel like this is in a really great place, great work so far on this @thrijith !

#### Initial activation of the plugin findings
- We discussed this a little in this thread, since we do have composer dependencies, we need to ensure we have a path forward to where we don't have to run `composer update`. Currently checking out this branch I had to manually run this of course, but I'd like to see what the path forward for this will be documented or updated in the PR.
- I encountered an interesting error when activating the plugin on this branch after running `composer update`. I got a white page that said "Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2".". My local PHP version is 8.0.2 but yet I see in composer we are setting `>=5.6`. I'm not fully clear why this error occurred but I found I needed to run `composer update --ignore-platform-reqs` to get the plugin to activate in WordPress. Not sure if anyone has any further thoughts on this and how to mitigate it further.

#### QA Results
A majority of our testing criteria for this plugin are passing, there were some spots that prior to this update we knew were not passing, these spots appear to still not be working which I feel is expected, but we should log a ticket on them if we don't already. The biggest pieces we need to address here are the cropping tools in the block editor, but it could be that these are issues outside of this update? I lean on @rickalee @jeffpaul on the final call on that.
- Upload via wp-admin/upload.php ✅
- Delete via wp-admin/upload.php ✅
- Upload via wp-admin/media-new.php ✅
- Delete via wp-admin/post.php?post=<post_id>&action=edit ✅
- Upload via Classic Editor ✅
- Delete via Classic Editor ✅
- Upload via Block Editor ✅
- Delete via Block Editor Media Library modal ✅
- Crop in Block Editor 🚫
    - I get a notice saying “Could not edit image. Unable to get meta information for file.” 
- Crop an already cropped image again - ensure appended/modified filename 🚫
    - I get a notice saying “Could not edit image. Unable to get meta information for file.”
- Crop in wp-admin/upload.php?item=<post_id>&mode=edit 🚫
    - Edited image did not upload to Azure Storage. 
    - DB updated with new modified image, but now image is blank as it returns 404.
    - This is a known previous bug that I don’t expect this current update to address.
- Crop an already cropped image again - ensure appended/modified filename 🚫
    - Edited image did not upload to Azure Storage. 
    - DB updated with new modified image, but now image is blank as it returns 404.
    - This is a known previous bug that I don’t expect this current update to address.
- Delete cropped image in wp-admin/upload.php ❎
    - This is partially tested. Since no cropped image was uploaded, I could only verify that the deletion of a cropped image (which failed to upload) also deleted the original image. Knowing that an edited image does have a new version created and it replaces the original with the new one, I would assume this feature exists, but we need cropped images working first for me to sign off on this.
- Resize an image in wp-admin/upload.php?item=<post_id>&mode=edit ✅
    - Resizing an image successfully generates a new image and replaced the original image in Azure Storage.
    - The replaced image had a new name generated.
- Rotate/Flip an image in wp-admin/upload.php?item=<post_id>&mode=edit 🚫
    - Image updates in the edit modal, but upon hitting save, it reverts back to the original image.
    - This was a known previous bug that I don’t expect this current update to address.
- Upload large ~150mb zip file 🚫
    - “Unexpected response from the server. The file may have been uploaded successfully. Check in the Media Library or reload the page.”
    - No evidence that the zip file was ever uploaded to Azure, nor found on the server.
    - NOTE: I had to explicitly allow zip files to be uploaded. This could be WordPress restricting it some how and not an issue with the Azure Storage plugin.
- Upload large ~150mb image ✅
- Upload two or more files with exact same file name and ensure -1, -2, etc appended. ✅
    - It should be noted that while the image file was made unique, Azure Storage appears to append a hash like string at the end of the file instead of incrementing with -1, -2, etc.
    - E.G. a file called test-image.png uploaded twice, the second image would have it’s name change to test-image-620d70ecb13da.png
- Delete duplicate image and ensure only that image is deleted. ✅
- Upload alternate file types: wav, mp3, mp4 ✅
- Upload files with special characters
    - %&\ ✅
        - File name is sanitized/escaped so that these special characters are removed from the file name. E.g. earned-$24-dollars.png is uploaded as earned-24-dollars.png.
    - Ãéñ accented characters ✅
        - File name is sanitized/escaped so that these accent characters are converted to the latin alphabet. E.g my-piñata.png is uploaded as my-pinata.png
    - Test frontend output (ensure esc_url_raw on theme functions) 🚫
        - This doesn’t appear to be needed as the file name is cleaned on upload.
- Upload on a multisite root site and subsite ✅
    - Image paths include /sites/{site_id}
- Upload on single site install ✅

**Comment by NicoleGeissinger** [comment]
@thrijith I ran another test but this time in a fresh WordPress install. I have some new updates to my original test.

- Crop in Block Editor ✅
- Crop an already cropped image again - ensure appended/modified filename ❎
    - Cropping an already cropped image it didn’t appear to work, but inspecting the media library I see the second cropped image I made. The block editor didn’t update. Viewing the front-end I also see the new crop I made.
    
I also performed tests against the latest version of Azure Storage and found the other places I had listed that didn't pass, also didn't pass so these are NOT new bugs tied to this update. I think we are okay moving past those for this update.

The only other thing I wanted to highlight is I think we'll want the autoload.php to ensure the required vendor dependencies are being loaded. Otherwise, we may need to manually load them.

Thanks!!

**Comment by NicoleGeissinger** [comment]
@thrijith I have tested your latest update with the autoload included in the repo. This is looking solid to me! I'm going to approve this MR from my end. Unsure if @rickalee wanted to give this a pass at all.

**Review by NicoleGeissinger — DISMISSED** [review]
After some testing and a few iterations, this PR looks great to me! Everything is working as expected on the new API.

**Comment by jeffpaul** [comment]
@rickalee @colegeissinger any further testing/review desired on this PR or is it good to merge and prepare for a release?

**Comment by jeffpaul** [comment]
@rickalee @colegeissinger noting that we might want to add something to README.md/readme.txt with anything new/changed in this update

**Comment by NicoleGeissinger** [comment]
@jeffpaul we are making progress on this finally. I'll work on getting the branch updated since there arr merge conflicts and also will make an update to the readme with any new/changes.

We have one more round of QA we want to run on a site and I'll update here soon once that is complete. Then I think we can finally move this forward!

**Review by NicoleGeissinger — APPROVED** [review]
This is now approved! @jeffpaul handing this over to you for next steps.

**Pull request merged**
