### PR TITLE
Resolve Issue with File Paths on Windows Server

### LINKED ISSUE #107: Upload problem on Windows Server
**Describe the bug**

Upload problem on Windows Server.
The following upload url is registered.
`https://containername.blob.core.windows.net/images/D:\home\site\wwwroot/wp-content/uploads/2019/11/image.png`

should be:
`https://containername.blob.core.windows.net/images/2019/11/image.png`

**Steps to Reproduce**

1. Install WordPress on Windows Server.
2. Install this plugin.
3. Upload image to Media Library.

**Expected behavior**

File upload is possible on Windows.

**Screenshots**

スクリーンショット 2019-11-24 21 18 51

**Environment information**
 - Server: Windows NT RD0003FF478ED3 10.0 build 14393 (Windows Server 2016) i586 (Microsoft Azure WebApps)
 - OS: MacOS 10.15.1
 - Browser and version: Safari 13.0.3
 - Plugins and version: 4.3.0
 - Theme and version: Twenty Seventeen 2.2

**Additional context**

### PR DESCRIPTION
**Pull request by rickalee**
Refactored use of DIRECTORY_SEPARATOR in upload process and implemented core function for when deleting local files to ensure better compatibility with Windows Server paths. 

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by nanasess** [comment]
@rickalee It's working as expected, thank you so match! 👍

**Comment by cally423** [comment]
Has this been resolved? When will the plugin release a new update?

**Comment by jeffpaul** [comment]
@cally423 we're working on testing the currently tagged PRs for the milesoned release, so if you're able to test this PR and confirm it works with your Windows environment then that'll help immensely!

**Review by dinhtungdu — APPROVED** [review]
Works great on Windows Server 2012

**Comment by cally423** [comment]
> @cally423 we're working on testing the currently tagged PRs for the milesoned release, so if you're able to test this PR and confirm it works with your Windows environment then that'll help immensely!

This PR testing out well - the issue seems to have been resolved. Thank you - excited for the new release!

**Comment by cally423** [comment]
This PR testing out well - the issue seems to have been resolved. Thank you - excited for the new release!

**Pull request merged**
