### PR TITLE
Fix upload problem on Windows Server

### LINKED ISSUE #107: Upload problem on Windows Server
**Describe the bug**

Upload problem on Windows Server.
The following upload url is registered.
`https://containername.blob.core.windows.net/images/D:\home\site\wwwroot/wp-content/uploads/2019/11/image.png`

should be:
`https://containername.blob.core.windows.net/images/2019/11/image.png`

**Steps to Reproduce**

1. Install WordPress on Windows Server.
2. Install this plugin.
3. Upload image to Media Library.

**Expected behavior**

File upload is possible on Windows.

**Screenshots**

スクリーンショット 2019-11-24 21 18 51

**Environment information**
 - Server: Windows NT RD0003FF478ED3 10.0 build 14393 (Windows Server 2016) i586 (Microsoft Azure WebApps)
 - OS: MacOS 10.15.1
 - Browser and version: Safari 13.0.3
 - Plugins and version: 4.3.0
 - Theme and version: Twenty Seventeen 2.2

**Additional context**

### PR DESCRIPTION
**Pull request by nanasess**
### Description of the Change

Path normalization to `Windows_Azure_Helper::wp_upload_dir()` and `windows_azure_storage_wp_generate_attachment_metadata()` functions.

Fixes #107, failure to replace `DIRECTORY_SEPARATOR`.

### Verification Process

1. Install WordPress on Windows Server.
2. Install this plugin.
3. Upload image to Media Library.
4. It worked.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

- #107

### CODE REVIEW

**Comment by jeffpaul** [comment]
@nanasess thanks again for the PR, we'll get this through review and back to you with any questions or concerns.

**Comment by jcphlux** [comment]
What is the holdup on this?

**Comment by jcphlux** [comment]
@nanasess I patched my plugin manually and I am up and running.  Thanks for the fix!

**Comment by jeffpaul** [comment]
@jcphlux we've been focused on reviewing/testing #109.  Thanks for confirming the fix in this branch resolves the issue for you, that'll help our review.

**Comment by cally423** [comment]
> @nanasess I patched my plugin manually and I am up and running. Thanks for the fix!

How did you patch manually? This plugin is no longer working for our sites.

**Comment by jcphlux** [comment]
> > @nanasess I patched my plugin manually and I am up and running. Thanks for the fix!
> 
> How did you patch manually? This plugin is no longer working for our sites.

I cloned/downloaded @nanasess fork and ftped the 2 files in this pr into my site.

**Comment by JuanQuijano** [comment]
One month ago and dont published the fix... please, please, please!!!

**Comment by RehanSaeed** [comment]
Any chance of getting this in and releasing an update. The latest version of the plugin is currently completely broken.

@rickalee Would appreciate a review.

**Comment by rickalee** [comment]
Working on review this week. Setting up a Windows Server environment to QA against and ensure no regressions for standard Linux environments.

**Comment by rickalee** [comment]
@nanasess @RehanSaeed @jcphlux 

Hi team,

Can you please review this branch and pull request? 

Opted to clean up our implementation and normalize paths earlier in upload process. 

Tested against Windows Server, Single Site and Multisite. Also ensured that files are deleted locally after successfully offloading to Azure. 

https://github.com/10up/windows-azure-storage/pull/111

**Comment by rickalee** [comment]
Resolved in #111 and merging into 4.3.1 release.

**Pull request closed without merging**
